# Generated by Django 6.0.3 on 2026-03-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="marks",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("mcq", "Multiple Choice"), ("descriptive", "Descriptive")],
                default="mcq",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_a",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_b",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_c",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_d",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
