# Generated by Django 6.0.3 on 2026-03-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="time_limit",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
